-- Projects from Hansani's projects list (kept private, outside the repo).
-- Order: professional first, then academic, each newest first.
-- Edits from the source: "Echonlabs" -> "EchonLabs"; "Post Sales" -> "Post-Sales";
-- "(Research Project)" / "(Group Project)" moved from titles to the start of the summary.

INSERT INTO project (slug, title, category, employer, role, summary, start_date, end_date, tech_stack, link_url, sort_order, published)
VALUES
(
    'cmss-contract-management-schedule-system',
    'CMSS - Contract Management Schedule System',
    'professional', 'Kaleris', 'Full-stack Engineer',
    'Application to load and manage contracts, create POs and PO shipments related to purchase orders with current customers (liquid and dry bulk shippers), and update the yard and trans-load management in real-time.',
    '2022-04-01', '2024-07-01',
    ARRAY['Angular', 'Java', 'Spring Boot', 'Microservices', 'EFK', 'Kafka', 'Docker', 'Jenkins', 'Kubernetes', 'AWS', 'PostgreSQL'],
    NULL, 1, TRUE
),
(
    'tcm-truck-carrier-management',
    'TCM - Truck Carrier Management',
    'professional', 'Kaleris', 'Full-stack Developer',
    'Central repository for all master data, ensuring all shippers, receivers, and carriers have one version of data. Transactions are processed in real-time, and all stakeholders can verify the details and identify exceptions.',
    '2022-04-01', '2024-07-01',
    ARRAY['Java 17', 'Spring', 'Gradle', 'Apache Tomcat', 'GWT', 'SmartGWT', 'PostgreSQL', 'AWS'],
    NULL, 2, TRUE
),
(
    'ez-cash',
    'Ez Cash',
    'professional', 'Axiata Digital Labs', 'Full-stack Developer',
    'A fintech product that enables users to perform a wide array of financial transactions including utility payments, merchant payments, bank deposits, and receive foreign remittances using a Dialog mobile phone.',
    '2021-07-01', '2022-03-01',
    ARRAY['Java 7', 'Spring MVC', 'Spring Boot', 'Express', 'Hibernate', 'Maven', 'Oracle Database', 'Docker', 'JSF', 'JSP', 'Apache Tomcat', 'SonarQube', 'REST', 'SOAP', 'JUnit', 'Mockito', 'Postman', 'REST Assured'],
    NULL, 3, TRUE
),
(
    'lesi-pay',
    'Lesi Pay',
    'professional', 'Axiata Digital Labs', 'Full-stack Developer',
    'A fintech application that provides device loan solutions (mobile phones, tablets) based on a customer ranking system for Dialog customers, where they can purchase them on a monthly installment scheme.',
    '2021-02-01', '2021-07-01',
    ARRAY['Java 8', 'Spring Boot', 'PostgreSQL', 'Microservices', 'Eureka', 'Zuul', 'Spring Security', 'Docker', 'RabbitMQ'],
    NULL, 4, TRUE
),
(
    'post-sales',
    'Post-Sales',
    'professional', 'EchonLabs', 'Full-stack Developer',
    'A reactive web application to manage customer issues and problems online and track the progress.',
    '2019-06-01', '2020-01-01',
    ARRAY['Angular', 'Express', 'Node.js', 'MongoDB'],
    NULL, 5, TRUE
),
(
    'prompting-for-security-llm-code-generation-in-angular',
    'Prompting for Security: LLM Code Generation in Angular',
    'academic', NULL, NULL,
    'Research project: Explored how different prompt engineering strategies affect the security of Angular code generated by LLMs.',
    '2025-03-01', '2025-07-01',
    ARRAY['Angular', 'TypeScript', 'SonarQube', 'Aikido', 'Snyk', 'AppScan', 'Prompt Engineering'],
    NULL, 6, TRUE
),
(
    'a-hybrid-approach-and-ant-colony-optimisation-for-early-stage-diabetes-prediction',
    'A Hybrid Approach and Ant Colony Optimisation for Early-Stage Diabetes Prediction',
    'academic', NULL, NULL,
    'Research project: Studied the impact of feature selection using the Ant Colony Optimisation algorithm to enhance clustering performance.',
    '2024-07-01', '2024-12-01',
    ARRAY['Python', 'Machine Learning', 'Ant Colony Algorithm', 'Clustering', 'sklearn'],
    NULL, 7, TRUE
),
(
    'responsive-web-application-to-collect-information-for-covid-19',
    'Responsive Web Application to Collect Information for COVID-19',
    'academic', NULL, NULL,
    'Group project: Developed a web application to collect health information during the COVID-19 pandemic.',
    '2020-04-01', '2020-06-01',
    ARRAY['Angular', 'Node.js', 'MongoDB', 'Express'],
    'https://github.com/sivantha96/health-counter', 8, TRUE
),
(
    'hand-movement-tracking-system-to-detect-drowning',
    'Hand Movement Tracking System to Detect Drowning',
    'academic', NULL, NULL,
    'Research project: A system to classify drowning and non-drowning situations using accelerometer data.',
    '2019-06-01', '2019-11-01',
    ARRAY['Arduino', 'Wi-Fi Module', 'Python', 'Keras', 'TensorFlow', 'Flask', 'CNN'],
    'https://github.com/hansaniperera/Drowning-Detection-System', 9, TRUE
);
